### ISSUE TITLE
chronosgl not showing on pub.dartlang.org

### ISSUE THREAD

**Issue by IssuesMigrator** [dart-lang/pub-dartlang#251]
_From [jda...@pcprogramming.com](https://code.google.com/u/110122036711105908093/) on September 21, 2014 22:51:18_

What steps will reproduce the problem? 1. visit pub.dartlang.org
2. search for chronosgl
3. the list count is 1, but there are no entries in the list What is the expected output? What do you see instead? an entry for chronosgl.  nothing.

What version of the product are you using? latest

On what operating system? win 8.1

What browser (if applicable)? all Please provide any additional information below.

_Original issue: http://code.google.com/p/dart/issues/detail?id=21028_

**Comment by rhulha** [comment]
yay, it seems we are back in the search results!

I hope it stays now...

I think you can close the issue now, (I hope haha)

**Comment by floitschG** [comment]
Please reopen if it happens again.
