### ISSUE TITLE
Recommend caret constraints in "Installing" tab

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/pub-dartlang#266]
Currently it recommends e.g.:

```yaml
dependencies:
  prompt: ">=0.1.3 <0.2.0"
```

It would be nice to recommend [caret constraints](https://www.dartlang.org/tools/pub/dependencies.html#caret-syntax) instead:

```yaml
dependencies:
  prompt: "^0.1.3"
```

Maybe could recommend both until enough folks have upgraded to dart `1.8.0` when ^ was introduced.

**Comment by zoechi** [comment]
Maybe suggest adding

```yaml
environment:
  sdk: ">=1.8.0"
```
to the second variant

**Comment by seaneagan** [comment]
@zoechi yep
