### ISSUE TITLE
Which directories under 'build' get a 'packages' entry during 'pub build'?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/pub-dartlang#272]
Apparently, 'pub build' does not fully support the use of subdirectories in the sense described below.  My interpretation is that 'pub build' should create more 'packages' symlinks/directories than it currently does.

The problem arises if you create a package and put a file that is intended to be used as a program (i.e., it contains a declaration of 'main') into a subdirectory of the directory given to 'pub build' (default 'web', in the example below it's 'test'):  The copy of this program that resides in the original directory ('test/subdir/my_test.dart') runs correctly, but the copy in build (build/test/subdir/my_test.dart) fails to run, because it makes an attempt to use a 'packages' directory that does not exist (build/test/subdir/packages).  I can make the program succeed by creating the 'packages' symlink under build/... to another 'packages' directory manually, and it seems likely to me that 'pub build' should have created that symlink.  I can also make the program succeed by giving an explicit --package-root, but it seems unlikely that this would be required (given that those 'packages' directories are created "everywhere else" by pub, and all other tests run without a --package-root from the package root directory).

You can inspect the details of this issue by fetching missing_packages.tgz (from the code.google.com site mentioned below) which is a near-minimal package exhibiting the problem.  This package was created by 'pub global run stagehand -o missing_packages consoleapp' and adjusted slightly, thus creating the situation that provokes the problem.  Check out and execute bin/run to see the commands that fail unexpectedly and compare with the ones that succeed.

**Comment by sethladd** [comment]
Hi Erik, This sounds like an issue for dartbug.com. (this repo is just for the site)

Would you mind filing it there and pasting the issue here?

**Comment by eernstg** [comment]
OK, it's at https://code.google.com/p/dart/issues/detail?id=22677.  I've removed the copy of missing_packages.tgz from the location indicated earlier, and edited the original description to point to the code.google.com issue where it is attached.

**Comment by eernstg** [comment]
Sure, done.

On Thu, Mar 5, 2015 at 5:52 PM, Seth Ladd <notifications@github.com> wrote:

> Hi Erik, This sounds like an issue for dartbug.com. (this repo is just
> for the site)
>
> Would you mind filing it there and pasting the issue here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/pub-dartlang/issues/272#issuecomment-77401715>
> .
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984
